---
- name: make sure rabbitmq server is up
  become: yes
  service:
    name: rabbitmq-server
    state: started

- name: make sure rabbitmq app is up
  become: yes
  command: rabbitmqctl start_app

- name: check if already in cluster
  become: yes
  command: rabbitmqctl cluster_status
  register: cluster_status
  changed_when: false

- include_tasks: join-cluster.yml
  when: cluster_status.stdout.find("rabbit@{{ rabbitmq_master }}") == -1 and (inventory_hostname != rabbitmq_master)