
# enable queues mirroring
- name: check if ha-mode is already enabled
  become: yes
  shell: rabbitmqctl list_policies
  register: list_policies
  changed_when: false

- name: set ha-mode to exactly two nodes for all queues for backup
  become: yes
  shell: rabbitmqctl set_policy ha-exactly-two ".*" '{"ha-mode":"exactly","ha-params":2,"ha-sync-mode":"automatic"}'
  register: res
  failed_when: res.rc != 0
  when: list_policies.stdout.find("ha-exactly-two") == -1